name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.152.0'
          extended: true

      - name: Build (custom domain)
        run: hugo --gc --minify --baseURL "https://andychang01.cn/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          cname: andychang01.cn       # 自动在 gh-pages 里生成 CNAME
          enable_jekyll: false        # 自动加 .nojekyll